version: '3.4'

services:
  app:
    image: busybox
    command: ip route show
    
    networks:
      app_net:
         ipv4_address: 172.16.237.2
networks:
  app_net:
    driver: bridge    
    ipam:
      driver: default
      config:
      - subnet: 172.16.237.0/24
      
      

      
        